version: '3.8'

services:
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: toor
      MONGO_INITDB_DATABASE: testdb

  python:
    build: .
    depends_on:
      - mongo
    ports:
      - "5000:5000"
    develop:
      watch:
        - action: sync+restart
          path: ./app
          target: /app
        - action: rebuild
          path: ./app/requirements.txt
        - action: rebuild
          path: ./Dockerfile

