name: Update submodules in main repo
on: [push]
jobs:
    update-submodules:
        runs-on: ubuntu-latest
        steps:
            - uses: runsascoded/update-submodules@v1
              with:
                token: ${{ secrets.ACTIONS_PAT }}
                repository: kuromiichi/AccesoADatos
